### ISSUE TITLE
Null output...

### ISSUE THREAD

**Issue by Merovex** [olegtarasov/get-tag#6] opened 2019-12-28 19:21 UTC
So, just trying this for the first time. There is no output.

**Comment by olegtarasov** [comment] 2020-02-28 13:05
@Merovex Hi! Are you still experiencing this problem? Please share your action config so we could start figuring out what went wrong.

**Comment by mandytrinh** [comment] 2020-04-07 02:13
Hi,
I'm also seeing this prints out a blank string
Here's my config

```
name: Test
on:
  push:
    branches:
      - test-branch
    tags: 
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get git tag
      uses: olegtarasov/get-tag@v2
      id: tagName
      with:
        tagname: ${{ steps.tagName.outputs.tag }}
    - name: Echoes tag
      run: echo tag is ${{ steps.tagName.outputs.tag }}
```

neither `echo tag is ${{ steps.tagName.outputs.tag }}` nor `echo tag is ${GIT_TAG_NAME}` prints anything

**Comment by olegtarasov** [comment] 2020-05-17 17:04
Closing since there was no reply and I can't reproduce the problem on my end.

**Closed by olegtarasov** 2020-05-17 17:04 UTC
Labels: invalid
